-- Problema di percorso minimo
-- Grafo con rami pesati -> trova il percorso a costo minimo
-- Voglio un programma che dato un elenco di costi mi crei il percorso minore
-- La struttura è sempre: strada A, strada B e Incrocio
-- L'ultimo elemento sarà 0 per facilitare l'albero