name:                animated
version:             0.1.0.0
github:              "githubuser/animated"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/animated#readme>

dependencies:
- base >= 4.7 && < 5
- GLFW-b >= 1.4.7.2
- gloss >= 1.9.3.1
- gloss-rendering >= 1.9.3.1
- mtl
- elerea
- random

library:
  source-dirs: src

executables:
  animated-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animated

tests:
  animated-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animated
